<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Commands\v1\" />
      <Folder Include="Queries\v1\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\OnlineSheduling.Domain\OnlineScheduling.Domain.csproj" />
      <ProjectReference Include="..\OnlineSheduling.Infra\OnlineScheduling.Infra.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Dapper.Contrib" Version="2.0.78" />
      <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
      <PackageReference Include="Scrutor" Version="4.2.2" />
    </ItemGroup>

</Project>
